// apps/app-angular/src/shared/components/header/header.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { HeaderAction, NavLink } from '@shibui-ui/ui/components/molecules/header/lib-header.types';

@Component({
  selector: 'app-header',
  imports: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  standalone: true,
  templateUrl: './header.html',
  styleUrl: './header.scss',
})
export class HeaderComponent {

  DEFAULT_LINKS: NavLink[] = [
    { id: 'componentes', label: 'Componentes', href: '/componentes' },
    { id: 'tokens', label: 'Tokens', href: '/tokens' },
    { id: 'filosofia', label: 'Filosofía', href: '/filosofia' },
    { id: 'about', label: 'Sobre mí', href: '/about' },
  ];
  
  DEFAULT_ACTIONS: HeaderAction[] = [
    { label: 'Empezar →', href: '#', variant: 'kintsugi' },
  ];
  

}

// apps/app-svelte/src/lib/Header.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { navigate } from './router';

  let headerEl: HTMLElement | null = $state(null);

  const LINKS = [
    { id: 'componentes', label: 'Componentes', href: '#/componentes' },
    { id: 'tokens',      label: 'Tokens',      href: '#/tokens'      },
    { id: 'filosofia',   label: 'Filosofía',   href: '#/filosofia'   },
    { id: 'about',       label: 'Sobre mí',    href: '#/about'       },
  ];

  const ACTIONS = [
    { label: 'Empezar →', href: '#/componentes', variant: 'kintsugi' },
  ];

  onMount(async () => {
    if (!headerEl) return;
    await customElements.whenDefined('lib-header');
    (headerEl as any).links   = LINKS;
    (headerEl as any).actions = ACTIONS;
  });
</script>

<lib-header
  bind:this={headerEl}
  variant="kintsugi"
  logo-mark="渋"
  brand-name="shibui"
  logo-href="#/"
  style="position: fixed; top: 0; left: 0; right: 0; z-index: var(--z-overlay);"
></lib-header>
