// apps/app-react/src/dev/KitchenSink/KitchenItem.tsx
import type { ReactNode } from 'react';
import { coverageOf } from './catalog';
import { StatusBadge } from './StatusBadge';

interface Props {
  name: string;
  note?: string;
  children: ReactNode;
}

export function KitchenItem({ name, note, children }: Props) {
  return (
    <article
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 'var(--lib-space-sm)',
        padding: 'var(--lib-space-md)',
        background: 'var(--bg-surface)',
        border: '1px solid var(--border-subtle)',
        borderRadius: 'var(--radius-sm, 2px)',
      }}
    >
      <header style={{ display: 'flex', alignItems: 'center', gap: 'var(--lib-space-sm)', flexWrap: 'wrap' }}>
        <h4 style={{ margin: 0, fontFamily: 'var(--lib-font-mono, monospace)', fontSize: '0.9rem', color: 'var(--text-primary)' }}>
          {name}
        </h4>
        <StatusBadge coverage={coverageOf(name)} />
        {note && <small style={{ color: 'var(--text-muted)' }}>{note}</small>}
      </header>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--lib-space-sm)', alignItems: 'flex-start' }}>
        {children}
      </div>
    </article>
  );
}

// apps/app-svelte/src/routes/kitchen/KitchenItem.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import StatusBadge from './StatusBadge.svelte';

  interface Props { name: string; note?: string; children: Snippet; }
  let { name, note = '', children }: Props = $props();
</script>

<article class="item">
  <header>
    <h4>{name}</h4>
    <StatusBadge {name} />
    {#if note}<small>{note}</small>{/if}
  </header>
  <div class="body">{@render children()}</div>
</article>

<style>
  .item {
    display: flex; flex-direction: column; gap: var(--lib-space-sm);
    padding: var(--lib-space-md);
    background: var(--bg-surface);
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-sm, 2px);
  }
  header { display: flex; align-items: center; gap: var(--lib-space-sm); flex-wrap: wrap; }
  h4 { margin: 0; font-family: var(--lib-font-mono, monospace); font-size: 0.9rem; color: var(--text-primary); }
  small { color: var(--text-muted); }
  .body { display: flex; flex-wrap: wrap; gap: var(--lib-space-sm); align-items: flex-start; }
</style>
