// apps/app-svelte/src/routes/tokens/ShadowsSection.svelte
<script lang="ts">
  import type { DesignTokenDto } from '../../lib/api/tokens';
  import TokenSection from './TokenSection.svelte';
  import TokenRow from './TokenRow.svelte';
  import DataStatus from './DataStatus.svelte';

  interface Props {
    tokens: DesignTokenDto[];
    loading: boolean;
    error: string | null;
  }
  let { tokens, loading, error }: Props = $props();
</script>

<TokenSection
  id="sombras"
  eyebrow="shadow"
  title="Escala de"
  accent="sombras"
  description="Cuatro niveles (sm → xl) basados en ink con opacidades variables para light y dark mode."
>
  <DataStatus {loading} {error} />

  {#each tokens as token (token.id)}
    <TokenRow {token}>
      {#snippet preview()}
        <span class="shadow-box" style="box-shadow:{token.value};"></span>
      {/snippet}
    </TokenRow>
  {/each}
</TokenSection>

<style>
  .shadow-box {
    width: 44px;
    height: 44px;
    flex-shrink: 0;
    background: var(--bg-elevated);
    border: 1px solid var(--border-subtle);
  }
</style>

// apps/app-react/src/features/tokens/components/ShadowsSection.tsx
import React from 'react';
import { TokenSection } from './_TokenSection';
import { TokenRow, LoadingText, ErrorText } from './_TokenRow';
import { useTokensByCategory } from '../../../data/api/domain/tokens/hooks/useTokens';

const ShadowsSection: React.FC = () => {
  const { isPending, isError, error, data } = useTokensByCategory('shadow');

  return (
    <TokenSection
      id="sombras"
      eyebrow="shadow"
      title={<>Escala de <em>sombras</em></>}
      description="Cuatro niveles (sm → xl) basados en ink con opacidades variables para light y dark mode."
    >
      {isPending && <LoadingText />}
      {isError && <ErrorText error={error} />}

      {data && data.map(t => (
        <TokenRow
          key={t.id}
          token={t}
          preview={
            <div
              style={{
                width: '44px',
                height: '44px',
                flexShrink: 0,
                background: 'oklch(88% 0.006 72deg)',
                borderRadius: '2px',
                boxShadow: t.value,
              }}
            />
          }
        />
      ))}
    </TokenSection>
  );
};

export default ShadowsSection;
