// apps/app-svelte/src/routes/kitchen/StatusBadge.svelte
<script lang="ts">
  import { coverageOf, type Coverage } from './catalog';

  interface Props { name: string; }
  let { name }: Props = $props();

  let cov = $derived<Coverage>(coverageOf(name));
  let dot = $derived(cov === 'semantic' ? '🟢' : cov === 'marker' ? '🔵' : '⚪');
</script>

<span class="badge {cov}" title="Katachi coverage: {cov}">{dot} {cov}</span>

<style>
  .badge {
    display: inline-flex; align-items: center; gap: 4px;
    padding: 2px 8px; border-radius: 4px;
    font-family: var(--lib-font-mono, monospace);
    font-size: 0.7rem; letter-spacing: 0.04em; white-space: nowrap;
  }
  .semantic { background: oklch(70% 0.15 145deg / 0.18); color: oklch(80% 0.18 145deg); }
  .marker   { background: oklch(70% 0.15 230deg / 0.18); color: oklch(80% 0.18 230deg); }
  .effect   { background: oklch(60% 0.02 270deg / 0.18); color: oklch(80% 0.02 270deg); }
</style>

// apps/app-react/src/dev/KitchenSink/StatusBadge.tsx
import type { Coverage } from './catalog';

const STYLES: Record<Coverage, { bg: string; fg: string; label: string; dot: string }> = {
  semantic: { bg: 'oklch(70% 0.15 145deg / 0.18)', fg: 'oklch(80% 0.18 145deg)', label: 'semantic', dot: '🟢' },
  marker:   { bg: 'oklch(70% 0.15 230deg / 0.18)', fg: 'oklch(80% 0.18 230deg)', label: 'marker',   dot: '🔵' },
  effect:   { bg: 'oklch(60% 0.02 270deg / 0.18)', fg: 'oklch(80% 0.02 270deg)', label: 'effect',   dot: '⚪' },
};

export function StatusBadge({ coverage }: { coverage: Coverage }) {
  const s = STYLES[coverage];
  return (
    <span
      title={`Katachi coverage: ${s.label}`}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 4,
        padding: '2px 8px',
        borderRadius: 4,
        fontFamily: 'var(--lib-font-mono, monospace)',
        fontSize: '0.7rem',
        letterSpacing: '0.04em',
        background: s.bg,
        color: s.fg,
        whiteSpace: 'nowrap',
      }}
    >
      {s.dot} {s.label}
    </span>
  );
}
