// apps/app-svelte/src/routes/Login.svelte
<script lang="ts">
  import { login } from '../lib/auth';
  import { navigate } from '../lib/router';

  let password = $state('');
  let error = $state(false);
  let shake = $state(false);

  function handleLogin() {
    if (login(password)) {
      navigate('/admin/kitchen-sink');
    } else {
      error = true;
      shake = true;
      setTimeout(() => (shake = false), 500);
    }
  }

  function onFormSubmit(e: Event) {
    e.preventDefault();
    handleLogin();
  }
</script>

<lib-background variant="ash-grid">
  <div class="login-wrapper">
    <div class="card-wrapper" class:is-shaking={shake}>
      <lib-glass-card variant="kaki" intensity="high">
        <form class="login-form" onsubmit={onFormSubmit}>

          <div class="brand">
            <span class="kanji">渋</span>
            <span class="access-message">admin · acceso restringido</span>
          </div>

          <lib-input
            type="password"
            label="Contraseña"
            placeholder="••••••••••"
            value={password}
            error={error}
            errorMessage="Contraseña incorrecta"
            on:ui-lib-input={(e) => { password = e.detail.value; error = false; }}
          ></lib-input>

          <lib-button variant="primary" on:ui-lib-click={handleLogin}>
            Entrar
          </lib-button>

        </form>
      </lib-glass-card>
    </div>
  </div>
</lib-background>

<style>
  .login-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
  }

  .card-wrapper {
    width: 100%;
    max-width: 380px;
  }

  .card-wrapper.is-shaking {
    animation: shake 0.4s ease;
  }

  .login-form {
    padding: var(--lib-space-2xl);
    display: flex;
    flex-direction: column;
    gap: var(--lib-space-xl);
  }

  .brand {
    display: flex;
    flex-direction: column;
    gap: var(--lib-space-xs);
  }

  .kanji {
    font-family: var(--lib-font-display);
    font-size: var(--text-3xl);
    font-weight: var(--weight-light);
    color: color-mix(in oklch, var(--color-kaki-500), transparent 40%);
    line-height: 1;
  }

  .access-message {
    font-family: var(--lib-font-mono);
    font-size: var(--text-xs);
    letter-spacing: var(--tracking-widest);
    text-transform: uppercase;
    color: var(--text-muted);
  }

  @keyframes shake {
    0%, 100% { transform: translateX(0); }
    20%       { transform: translateX(-8px); }
    40%       { transform: translateX(8px); }
    60%       { transform: translateX(-5px); }
    80%       { transform: translateX(5px); }
  }
</style>

// apps/app-tauri/src/pages/login/index.tsx
import { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { LibBackground, LibButton } from '@shibui-ui/ui/react';
import { useAuth } from '../../core/hooks/useAuth';

export function LoginPage() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [password, setPassword] = useState('');
  const [error, setError] = useState(false);
  const [shake, setShake] = useState(false);

  const from = (location.state as { from?: Location })?.from?.pathname ?? '/admin';

  const handleSubmit = () => {
    const ok = login(password);
    if (ok) {
      navigate(from, { replace: true });
    } else {
      setError(true);
      setShake(true);
      setTimeout(() => setShake(false), 500);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') handleSubmit();
  };

  return (
    <LibBackground variant="ash-grid">
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
      }}>
        <div
          style={{
            width: '100%',
            maxWidth: '380px',
            padding: '2.5rem',
            background: 'rgba(18, 14, 10, 0.85)',
            border: `1px solid ${error ? 'rgba(220, 60, 60, 0.4)' : 'rgba(255,255,255,0.07)'}`,
            backdropFilter: 'blur(12px)',
            display: 'flex',
            flexDirection: 'column',
            gap: '1.75rem',
            animation: shake ? 'shake 0.4s ease' : undefined,
          }}
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
            <span style={{
              fontFamily: 'var(--lib-font-display, "Cormorant Garamond", serif)',
              fontSize: '2rem',
              fontWeight: 300,
              color: 'rgba(184, 90, 30, 0.6)',
              lineHeight: 1,
            }}>
              渋
            </span>
            <span style={{
              fontFamily: 'var(--lib-font-mono, "DM Mono", monospace)',
              fontSize: '0.6rem',
              letterSpacing: '0.24em',
              textTransform: 'uppercase',
              color: 'rgba(250,247,244,0.2)',
            }}>
              admin · acceso restringido
            </span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <label style={{
              fontFamily: 'var(--lib-font-mono, "DM Mono", monospace)',
              fontSize: '0.6rem',
              letterSpacing: '0.2em',
              textTransform: 'uppercase',
              color: 'rgba(250,247,244,0.25)',
            }}>
              Contraseña
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => { setPassword(e.target.value); setError(false); }}
              onKeyDown={handleKeyDown}
              autoFocus
              style={{
                background: 'rgba(255,255,255,0.04)',
                border: `1px solid ${error ? 'rgba(220,60,60,0.5)' : 'rgba(255,255,255,0.08)'}`,
                color: 'rgba(250,247,244,0.75)',
                padding: '0.625rem 0.875rem',
                fontFamily: 'var(--lib-font-mono, "DM Mono", monospace)',
                fontSize: '0.875rem',
                letterSpacing: '0.08em',
                outline: 'none',
                width: '100%',
                boxSizing: 'border-box',
                transition: 'border-color 0.2s',
              }}
              placeholder="••••••••••"
            />
            {error && (
              <span style={{
                fontFamily: 'var(--lib-font-mono)',
                fontSize: '0.6rem',
                letterSpacing: '0.14em',
                color: 'rgba(220,60,60,0.7)',
                textTransform: 'uppercase',
              }}>
                Contraseña incorrecta
              </span>
            )}
          </div>

          <LibButton variant="primary" onUiLibClick={handleSubmit}>
            Entrar
          </LibButton>
        </div>
      </div>

      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          20%       { transform: translateX(-8px); }
          40%       { transform: translateX(8px); }
          60%       { transform: translateX(-5px); }
          80%       { transform: translateX(5px); }
        }
      `}</style>
    </LibBackground>
  );
}
