// apps/app-svelte/src/routes/tokens/TokenRow.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { DesignTokenDto } from '../../lib/api/tokens';

  interface Props {
    token: DesignTokenDto;
    /** Muestra visual opcional a la izquierda (swatch, sombra, radio…). */
    preview?: Snippet;
  }
  let { token, preview }: Props = $props();
</script>

<div class="row" class:row--preview={preview}>
  {#if preview}
    <div class="preview">{@render preview()}</div>
  {/if}
  <code class="var">{token.cssVar}</code>
  <code class="value">{token.value}</code>
  <span class="desc">{token.description}</span>
</div>

<style>
  .row {
    display: grid;
    grid-template-columns: 1fr 1.2fr 2fr;
    gap: 1rem;
    align-items: center;
    padding: 0.6rem 0;
    border-bottom: 1px solid var(--border-subtle);
  }
  .row--preview {
    grid-template-columns: 48px 1fr 1.2fr 2fr;
  }

  .preview {
    flex-shrink: 0;
    display: flex;
  }

  .var {
    font-family: var(--lib-font-mono);
    font-size: 0.68rem;
    color: var(--text-accent);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .value {
    font-family: var(--lib-font-mono);
    font-size: 0.65rem;
    color: var(--text-secondary);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .desc {
    font-family: var(--lib-font-body);
    font-size: 0.75rem;
    color: var(--text-muted);
    line-height: 1.4;
  }
</style>

// apps/app-react/src/pages/tokens/templates/_TokenRow.tsx
import React from 'react';
import type { DesignTokenDto } from '../../../data/api/domain/tokens/api/tokens.api';

interface TokenRowProps {
  token: DesignTokenDto;
  preview?: React.ReactNode;
}

export const TokenRow: React.FC<TokenRowProps> = ({ token, preview }) => (
  <div
    style={{
      display: 'grid',
      gridTemplateColumns: preview ? '48px 1fr 1.2fr 2fr' : '1fr 1.2fr 2fr',
      gap: '1rem',
      alignItems: 'center',
      padding: '0.6rem 0',
      borderBottom: '1px solid color-mix(in oklch, var(--color-washi-700) 25%, transparent)',
    }}
  >
    {preview && <div style={{ flexShrink: 0 }}>{preview}</div>}
    <code
      style={{
        fontFamily: 'var(--lib-font-mono)',
        fontSize: '0.68rem',
        color: 'var(--color-kaki-300)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
      }}
    >
      {token.cssVar}
    </code>
    <code
      style={{
        fontFamily: 'var(--lib-font-mono)',
        fontSize: '0.65rem',
        color: 'var(--text-secondary)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        opacity: 0.75,
      }}
    >
      {token.value}
    </code>
    <span
      style={{
        fontFamily: 'var(--lib-font-body)',
        fontSize: '0.75rem',
        color: 'var(--text-muted)',
        lineHeight: '1.4',
      }}
    >
      {token.description}
    </span>
  </div>
);

interface SubHeaderProps {
  label: string;
  first?: boolean;
}

export const SubHeader: React.FC<SubHeaderProps> = ({ label, first }) => (
  <div
    style={{
      fontFamily: 'var(--lib-font-mono)',
      fontSize: '0.58rem',
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      color: 'color-mix(in oklch, var(--color-kaki-400) 45%, transparent)',
      borderBottom: '1px solid color-mix(in oklch, var(--color-washi-700) 35%, transparent)',
      paddingBottom: '0.4rem',
      marginBottom: '0.75rem',
      marginTop: first ? '0' : '2rem',
    }}
  >
    {label}
  </div>
);

export const LoadingText: React.FC<{ label?: string }> = ({ label }) => (
  <span
    style={{
      fontFamily: 'var(--lib-font-mono)',
      fontSize: '0.72rem',
      color: 'var(--text-muted)',
    }}
  >
    Cargando{label ? ` ${label}` : ''}…
  </span>
);

export const ErrorText: React.FC<{ error: Error | null }> = ({ error }) => (
  <span
    style={{
      fontFamily: 'var(--lib-font-mono)',
      fontSize: '0.72rem',
      color: 'color-mix(in oklch, red 70%, white)',
    }}
  >
    Error: {error?.message ?? 'desconocido'}
  </span>
);
