// apps/app-react/src/features/tokens/components/SpacingSection.tsx
import React from 'react';
import { TokenSection } from './_TokenSection';
import { LoadingText, ErrorText } from './_TokenRow';
import { useTokensByCategory } from '../../../data/api/domain/tokens/hooks/useTokens';

function extractPx(desc: string): number {
  const m = desc.match(/(\d+)px/);
  return m ? parseInt(m[1]) : 0;
}

const SpacingSection: React.FC = () => {
  const { isPending, isError, error, data } = useTokensByCategory('spacing');

  const maxPx = 32;

  return (
    <TokenSection
      id="espaciado"
      eyebrow="spacing"
      title={<>Escala de <em>espaciado</em></>}
      description="Unidad base de 0.25 rem con escala multiplicativa: xs → xl."
    >
      {isPending && <LoadingText />}
      {isError && <ErrorText error={error} />}

      {data && data.map(t => {
        const px = extractPx(t.description);
        const barWidth = px > 0 ? Math.max((px / maxPx) * 180, 4) : 4;
        return (
          <div
            key={t.id}
            style={{
              display: 'grid',
              gridTemplateColumns: '190px 220px 1fr',
              gap: '1rem',
              alignItems: 'center',
              padding: '0.65rem 0',
              borderBottom: '1px solid color-mix(in oklch, var(--color-washi-700) 25%, transparent)',
            }}
          >
            <code style={{ fontFamily: 'var(--lib-font-mono)', fontSize: '0.68rem', color: 'var(--text-accent)' }}>
              {t.cssVar}
            </code>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
              <div
                style={{
                  height: '18px',
                  width: `${barWidth}px`,
                  background: 'var(--text-accent)',
                  opacity: 0.65,
                  borderRadius: '1px',
                  flexShrink: 0,
                }}
              />
              <code style={{ fontFamily: 'var(--lib-font-mono)', fontSize: '0.63rem', color: 'var(--text-secondary)', opacity: 0.7, whiteSpace: 'nowrap' }}>
                {px > 0 ? `${px}px` : t.value}
              </code>
            </div>
            <span style={{ fontFamily: 'var(--lib-font-body)', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              {t.description}
            </span>
          </div>
        );
      })}
    </TokenSection>
  );
};

export default SpacingSection;

// apps/app-svelte/src/routes/tokens/SpacingSection.svelte
<script lang="ts">
  import type { DesignTokenDto } from '../../lib/api/tokens';
  import TokenSection from './TokenSection.svelte';
  import DataStatus from './DataStatus.svelte';

  interface Props {
    tokens: DesignTokenDto[];
    loading: boolean;
    error: string | null;
  }
  let { tokens, loading, error }: Props = $props();

  const MAX_PX = 32;
  const BAR_MAX = 180;

  /** El px real vive en la descripción del token («…— 8px»). */
  function extractPx(description: string): number {
    const match = description.match(/(\d+)px/);
    return match ? Number.parseInt(match[1], 10) : 0;
  }

  let rows = $derived(
    tokens.map((token) => {
      const px = extractPx(token.description);
      return {
        token,
        px,
        barWidth: px > 0 ? Math.max((px / MAX_PX) * BAR_MAX, 4) : 4,
      };
    })
  );
</script>

<TokenSection
  id="espaciado"
  eyebrow="spacing"
  title="Escala de"
  accent="espaciado"
  description="Unidad base de 0.25 rem con escala multiplicativa: xs → xl."
>
  <DataStatus {loading} {error} />

  {#each rows as { token, px, barWidth } (token.id)}
    <div class="row">
      <code class="var">{token.cssVar}</code>
      <div class="bar-cell">
        <span class="bar" style="width:{barWidth}px;"></span>
        <code class="value">{px > 0 ? `${px}px` : token.value}</code>
      </div>
      <span class="desc">{token.description}</span>
    </div>
  {/each}
</TokenSection>

<style>
  .row {
    display: grid;
    grid-template-columns: 190px 220px 1fr;
    gap: 1rem;
    align-items: center;
    padding: 0.65rem 0;
    border-bottom: 1px solid var(--border-subtle);
  }

  .var {
    font-family: var(--lib-font-mono);
    font-size: 0.68rem;
    color: var(--text-accent);
  }

  .bar-cell {
    display: flex;
    align-items: center;
    gap: 0.6rem;
  }

  .bar {
    height: 18px;
    background: var(--text-accent);
    opacity: 0.65;
    flex-shrink: 0;
  }

  .value {
    font-family: var(--lib-font-mono);
    font-size: 0.63rem;
    color: var(--text-secondary);
    white-space: nowrap;
  }

  .desc {
    font-family: var(--lib-font-body);
    font-size: 0.75rem;
    color: var(--text-muted);
  }
</style>
