// apps/app-react/src/pages/tokens/templates/ZIndexSection.tsx
import React from 'react';
import { TokenSection } from './_TokenSection';
import { LoadingText, ErrorText } from './_TokenRow';
import { useTokensByCategory } from '../../../data/api/domain/tokens/hooks/useTokens';

const MAX_Z = 400;

const ZIndexSection: React.FC = () => {
  const { isPending, isError, error, data } = useTokensByCategory('z-index');

  return (
    <TokenSection
      id="z-index"
      eyebrow="z-index"
      title={<>Capas de <em>apilamiento</em></>}
      description="Seis niveles desde base (0) hasta tooltip (400) para gestionar la pila de renderizado."
    >
      {isPending && <LoadingText />}
      {isError && <ErrorText error={error} />}

      {data && data.map(t => {
        const zVal = parseInt(t.value) || 0;
        const barPct = (zVal / MAX_Z) * 100;
        return (
          <div
            key={t.id}
            style={{
              display: 'grid',
              gridTemplateColumns: '120px 52px 180px 1fr',
              gap: '1rem',
              alignItems: 'center',
              padding: '0.65rem 0',
              borderBottom: '1px solid color-mix(in oklch, var(--color-washi-700) 25%, transparent)',
            }}
          >
            <code style={{ fontFamily: 'var(--lib-font-mono)', fontSize: '0.68rem', color: 'var(--color-kaki-300)' }}>
              {t.cssVar}
            </code>
            <code style={{ fontFamily: 'var(--lib-font-mono)', fontSize: '0.68rem', color: 'var(--text-secondary)', opacity: 0.7 }}>
              {t.value}
            </code>
            <div
              style={{
                height: '6px',
                background: 'color-mix(in oklch, var(--color-washi-700) 30%, transparent)',
                borderRadius: '2px',
                overflow: 'hidden',
              }}
            >
              <div
                style={{
                  height: '100%',
                  width: `${Math.max(barPct, 1)}%`,
                  background: `color-mix(in oklch, var(--color-kaki-500) ${30 + barPct * 0.7}%, var(--color-kaki-300))`,
                  borderRadius: '2px',
                }}
              />
            </div>
            <span style={{ fontFamily: 'var(--lib-font-body)', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              {t.description}
            </span>
          </div>
        );
      })}
    </TokenSection>
  );
};

export default ZIndexSection;

// apps/app-svelte/src/routes/tokens/ZIndexSection.svelte
<script lang="ts">
  import type { DesignTokenDto } from '../../lib/api/tokens';
  import TokenSection from './TokenSection.svelte';
  import DataStatus from './DataStatus.svelte';

  interface Props {
    tokens: DesignTokenDto[];
    loading: boolean;
    error: string | null;
  }
  let { tokens, loading, error }: Props = $props();

  const MAX_Z = 400;

  let rows = $derived(
    tokens.map((token) => {
      const z = Number.parseInt(token.value, 10) || 0;
      return { token, pct: Math.max((z / MAX_Z) * 100, 1) };
    })
  );
</script>

<TokenSection
  id="z-index"
  eyebrow="z-index"
  title="Capas de"
  accent="apilamiento"
  description="Seis niveles desde base (0) hasta tooltip (400) para gestionar la pila de renderizado."
>
  <DataStatus {loading} {error} />

  {#each rows as { token, pct } (token.id)}
    <div class="row">
      <code class="var">{token.cssVar}</code>
      <code class="value">{token.value}</code>
      <span class="track">
        <span class="fill" style="width:{pct}%;"></span>
      </span>
      <span class="desc">{token.description}</span>
    </div>
  {/each}
</TokenSection>

<style>
  .row {
    display: grid;
    grid-template-columns: 120px 52px 180px 1fr;
    gap: 1rem;
    align-items: center;
    padding: 0.65rem 0;
    border-bottom: 1px solid var(--border-subtle);
  }

  .var {
    font-family: var(--lib-font-mono);
    font-size: 0.68rem;
    color: var(--text-accent);
  }

  .value {
    font-family: var(--lib-font-mono);
    font-size: 0.68rem;
    color: var(--text-secondary);
  }

  .track {
    height: 6px;
    background: var(--border-subtle);
    overflow: hidden;
    display: block;
  }

  .fill {
    height: 100%;
    display: block;
    background: var(--text-accent);
  }

  .desc {
    font-family: var(--lib-font-body);
    font-size: 0.75rem;
    color: var(--text-muted);
  }
</style>
